library("tidyverse")
names <- c("Peter","Alfred","Emma","Joseph")
ages <- c(18,23,19,25)
people <- data.frame(names,ages)
head(people)
str(people)
glimpse(people)
colnames(people)
mutate(people, age_in_20 = ages + 20)
apps <- c("whatsapp","X","Youtube","Linkedin","facebook")
rank <- c(5,4,5,4,1)
apps_rank <- data.frame(apps,rank)
glimpse(apps_rank)
str(apps_rank)
